version: 2

models:
  - name: dim_deputados
    description: "Dimension table for deputados with SCD Type 2 implementation"
    columns:
      - name: sk_deputado
        description: "Surrogate key for deputado (includes temporal dimension)"
        data_tests:
          - not_null
          - unique
      - name: nk_deputado
        description: "Natural key - deputado ID"
        data_tests:
          - not_null
      - name: nome_deputado
        description: "Deputy name"
        data_tests:
          - not_null
      - name: sigla_uf
        description: "State abbreviation"
        data_tests:
          - accepted_values:
              values: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
      - name: data_inicio_vigencia
        description: "Start date of validity period"
        data_tests:
          - not_null
      - name: data_fim_vigencia
        description: "End date of validity period"
        data_tests:
          - not_null
      - name: is_current
        description: "Flag indicating if this is the current record"
        data_tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: data_nascimento
        description: "Birth date"
      - name: sexo
        description: "Gender"
        data_tests:
          - accepted_values:
              values: ['M', 'F', 'MASCULINO', 'FEMININO']
              config:
                severity: warn

    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - nk_deputado
            - data_inicio_vigencia
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
          max_value: 50000

  - name: dim_fornecedores
    description: "Dimension table for suppliers/vendors"
    columns:
      - name: sk_fornecedor
        description: "Surrogate key for fornecedor"
        data_tests:
          - not_null
          - unique
      - name: nk_fornecedor
        description: "Natural key - CNPJ/CPF do fornecedor"
      - name: nome_fornecedor
        description: "Supplier name"
        data_tests:
          - not_null
      - name: data_carga
        description: "Load date"
        data_tests:
          - not_null

    data_tests:
      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1
