version: 2

sources:
  - name: camara_raw
    schema: raw
    tables:
      - name: deputados_detalhes
        description: "Current details of all deputados"
        columns:
          - name: id
            description: "Unique identifier for deputado"
            data_tests:
              - not_null
              - unique
          - name: cpf
            description: "CPF number"
          - name: nome_civil
            description: "Civil name"
            data_tests:
              - not_null
          - name: ultimo_status_id_legislatura
            description: "Current legislature ID"

      - name: deputado_historico
        description: "Historical status changes of deputados"
        columns:
          - name: deputado_id
            description: "Deputado identifier"
            data_tests:
              - not_null
          - name: data_hora
            description: "Timestamp of status change"
            data_tests:
              - not_null
          - name: id_legislatura
            description: "Legislature period ID"
          - name: sigla_partido
            description: "Political party"
          - name: sigla_uf
            description: "State abbreviation"

      - name: despesas
        description: "Raw expenses data from deputados"
        columns:
          - name: deputado_id
            description: "Foreign key to deputados"
            data_tests:
              - not_null
          - name: cod_documento
            description: "Document code"

      - name: proposicoes
        description: "Legislative propositions data"
        columns:
          - name: id
            description: "Unique proposition identifier"
            data_tests:
              - not_null
              - unique
          - name: numero
            description: "Proposition number"
          - name: ano
            description: "Year"
          - name: siglaTipo
            description: "Proposition type abbreviation"

      - name: eventos
        description: "Parliamentary events data"
        columns:
          - name: id
            description: "Unique event identifier"
            data_tests:
              - not_null
              - unique
          - name: dataHoraInicio
            description: "Event start datetime"
          - name: situacao
            description: "Event status"

      - name: licitacoes
        description: "Bidding processes data"
        columns:
          - name: idLicitacao
            description: "Unique bidding identifier"
            data_tests:
              - not_null
              - unique
          - name: numero
            description: "Bidding number"
          - name: ano
            description: "Year"

      - name: proposicoes_autores
        description: "Authors of legislative propositions"
        columns:
          - name: idProposicao
            description: "Proposition identifier"
            data_tests:
              - not_null
          - name: idDeputadoAutor
            description: "Author deputy identifier"
            data_tests:
              - not_null

      - name: proposicoes_temas
        description: "Thematic classification of propositions"
        columns:
          - name: uriProposicao
            description: "Proposition URI"
            data_tests:
              - not_null
          - name: codTema
            description: "Theme code"
            data_tests:
              - not_null

      - name: proposicoes_tramitacoes
        description: "Legislative process steps and tramitation history"
        columns:
          - name: proposicao_id
            description: "Proposition identifier"
            data_tests:
              - not_null
          - name: sequencia
            description: "Sequence number of tramitation step"
            data_tests:
              - not_null
          - name: data_hora
            description: "Tramitation datetime"
            data_tests:
              - not_null
          - name: descricao_tramitacao
            description: "Tramitation description"
          - name: sigla_orgao
            description: "Organ abbreviation"
          - name: ambito
            description: "Tramitation scope"
          - name: regime
            description: "Processing regime"

      - name: votacoes
        description: "Voting sessions data"
        columns:
          - name: id
            description: "Unique voting session identifier"
            data_tests:
              - not_null
              - unique
          - name: data
            description: "Voting date"
            data_tests:
              - not_null
          - name: dataHoraRegistro
            description: "Registration datetime"
          - name: aprovacao
            description: "Voting result"
          - name: votosSim
            description: "Yes votes count"
          - name: votosNao
            description: "No votes count"
          - name: votosOutros
            description: "Other votes count"
          - name: idOrgao
            description: "Organ ID"
          - name: siglaOrgao
            description: "Organ abbreviation"

      - name: votos
        description: "Individual deputy votes"
        columns:
          - name: votacao_id
            description: "Voting session identifier"
            data_tests:
              - not_null
          - name: deputado_id
            description: "Deputy identifier"
            data_tests:
              - not_null
          - name: tipoVoto
            description: "Vote type"
            data_tests:
              - not_null
          - name: dataRegistroVoto
            description: "Vote registration datetime"
            data_tests:
              - not_null

models:
  - name: stg_deputados_detalhes
    description: "Staging table for deputy details with standardized fields"
    columns:
      - name: deputado_id
        description: "Unique deputy identifier"
        data_tests:
          - not_null
          - unique
      - name: nome_civil
        description: "Civil name (standardized)"
        data_tests:
          - not_null
      - name: nome_eleitoral
        description: "Electoral name (standardized)"
      - name: cpf
        description: "CPF number (validated format)"
      - name: partido_atual
        description: "Current political party (standardized)"
      - name: uf_atual
        description: "Current state (standardized)"
        data_tests:
          - accepted_values:
              values: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
      - name: legislatura_atual
        description: "Current legislature ID"
        data_tests:
          - not_null

  - name: stg_deputado_historico
    description: "Staging table for deputy historical status changes"
    columns:
      - name: deputado_id
        description: "Foreign key to deputies"
        data_tests:
          - not_null
      - name: data_status
        description: "Status change date (standardized)"
        data_tests:
          - not_null
      - name: legislatura_id
        description: "Legislature period ID"
      - name: partido
        description: "Political party (standardized)"
      - name: uf
        description: "State (standardized)"
        data_tests:
          - accepted_values:
              values: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
      - name: situacao
        description: "Status description (standardized)"

  - name: stg_despesas
    description: "Staging table for deputy expenses with standardized categories"
    columns:
      - name: deputado_id
        description: "Foreign key to deputies"
        data_tests:
          - not_null
      - name: ano
        description: "Expense year"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2008
              max_value: 2030
      - name: mes
        description: "Expense month"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      - name: tipo_despesa
        description: "Expense type (standardized)"
        data_tests:
          - not_null
      - name: valor_documento
        description: "Document value (cleaned)"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: valor_glosa
        description: "Gloss value (cleaned)"
      - name: valor_liquido
        description: "Net value (calculated)"
        data_tests:
          - not_null

  - name: stg_votacoes
    description: "Staging table for voting sessions with standardized results"
    columns:
      - name: votacao_id
        description: "Unique voting session identifier"
        data_tests:
          - not_null
          - unique
      - name: proposicao_id
        description: "Related proposition ID"
      - name: data_votacao
        description: "Voting date (standardized)"
        data_tests:
          - not_null
      - name: resultado
        description: "Voting result (standardized)"
        data_tests:
          - not_null
          - accepted_values:
              values: ['APROVADA', 'REJEITADA', 'NAO_VOTADA', 'PREJUDICADA']
      - name: votos_sim
        description: "Yes votes count"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: votos_nao
        description: "No votes count"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: votos_outros
        description: "Other votes count (abstentions, obstructions)"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: orgao_votacao
        description: "Voting organ (standardized)"
      - name: ano
        description: "Year"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2000
              max_value: 2030
      - name: mes
        description: "Month"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

  - name: stg_votos
    description: "Staging table for individual deputy votes"
    columns:
      - name: votacao_id
        description: "Foreign key to voting sessions"
        data_tests:
          - not_null
      - name: deputado_id
        description: "Foreign key to deputados"
        data_tests:
          - not_null
      - name: tipo_voto
        description: "Vote type (standardized)"
        data_tests:
          - not_null
          - accepted_values:
              values: ['SIM', 'NÃO', 'NAO', 'ABSTENÇÃO', 'ABSTENCAO', 'OBSTRUÇÃO', 'OBSTRUCAO', 'ART. 17']
      - name: data_registro_voto
        description: "Vote registration timestamp"
        data_tests:
          - not_null
      - name: ano
        description: "Year"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2000
              max_value: 2030
      - name: mes
        description: "Month"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

  - name: stg_proposicoes_tramitacoes
    description: "Staging table for legislative process steps"
    columns:
      - name: proposicao_id
        description: "Proposition identifier"
        data_tests:
          - not_null
      - name: sequencia
        description: "Sequence number"
        data_tests:
          - not_null
      - name: data_tramitacao
        description: "Tramitação timestamp"
        data_tests:
          - not_null
      - name: descricao_tramitacao
        description: "Tramitação description (standardized)"
      - name: sigla_orgao
        description: "Organ/committee abbreviation (standardized)"
      - name: ambito
        description: "Scope of tramitação (standardized)"
      - name: regime
        description: "Processing regime (standardized)"
      - name: ano
        description: "Year"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2000
              max_value: 2030
      - name: mes
        description: "Month"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12

  - name: stg_proposicoes
    description: "Staging table for legislative propositions"
    columns:
      - name: proposicao_id
        description: "Unique proposition identifier"
        data_tests:
          - not_null
          - unique
      - name: sigla_tipo
        description: "Proposition type abbreviation"
        data_tests:
          - not_null
      - name: numero
        description: "Proposition number"
        data_tests:
          - not_null
      - name: ano
        description: "Year"
        data_tests:
          - not_null
      - name: ementa
        description: "Proposition summary"
        data_tests:
          - not_null
      - name: data_apresentacao
        description: "Presentation date"
        data_tests:
          - not_null

  - name: stg_eventos
    description: "Staging table for parliamentary events"
    columns:
      - name: evento_id
        description: "Unique event identifier"
        data_tests:
          - not_null
          - unique
      - name: data_hora_inicio
        description: "Event start datetime"
        data_tests:
          - not_null
      - name: situacao
        description: "Event status"
      - name: descricao
        description: "Event description"

  - name: stg_licitacoes
    description: "Staging table for bidding processes"
    columns:
      - name: licitacao_id
        description: "Unique bidding identifier"
        data_tests:
          - not_null
          - unique
      - name: numero
        description: "Bidding number"
        data_tests:
          - not_null
      - name: ano
        description: "Year"
        data_tests:
          - not_null
      - name: valor_estimado
        description: "Estimated value"
      - name: valor_contratado
        description: "Contracted value"

  - name: stg_proposicoes_autores
    description: "Staging table for proposition authors"
    columns:
      - name: proposicao_id
        description: "Proposition identifier"
        data_tests:
          - not_null
      - name: deputado_autor_id
        description: "Author deputy identifier"
        data_tests:
          - not_null
      - name: eh_proponente
        description: "Whether the author is the main proponent"
        data_tests:
          - not_null

  - name: stg_proposicoes_temas
    description: "Staging table for proposition themes"
    columns:
      - name: proposicao_id
        description: "Proposition identifier"
        data_tests:
          - not_null
      - name: cod_tema
        description: "Theme code"
        data_tests:
          - not_null
      - name: tema
        description: "Theme description"
        data_tests:
          - not_null
