version: 2

sources:
  - name: camara_raw
    schema: raw
    tables:
      - name: deputados_detalhes
        description: "Current details of all deputados"
        columns:
          - name: id
            description: "Unique identifier for deputado"
            data_tests:
              - not_null
              - unique
          - name: cpf
            description: "CPF number"
          - name: nome_civil
            description: "Civil name"
            data_tests:
              - not_null
          - name: ultimo_status_id_legislatura
            description: "Current legislature ID"

      - name: deputado_historico
        description: "Historical status changes of deputados"
        columns:
          - name: deputado_id
            description: "Deputado identifier"
            data_tests:
              - not_null
          - name: data_hora
            description: "Timestamp of status change"
            data_tests:
              - not_null
          - name: id_legislatura
            description: "Legislature period ID"
          - name: sigla_partido
            description: "Political party"
          - name: sigla_uf
            description: "State abbreviation"

      - name: despesas
        description: "Raw expenses data from deputados"
        columns:
          - name: deputado_id
            description: "Foreign key to deputados"
            data_tests:
              - not_null
          - name: cod_documento
            description: "Document code"
            data_tests:
              - not_null
          - name: data_documento
            description: "Document date"
            data_tests:
              - not_null
          - name: valor_documento
            description: "Document value"
            data_tests:
              - not_null

models:
  - name: stg_deputados_detalhes
    description: "Staging table for current deputados details"
    columns:
      - name: deputado_id
        description: "Unique identifier for deputado"
        data_tests:
          - not_null
          - unique
      - name: cpf
        description: "CPF number (standardized)"
      - name: nome_civil
        description: "Civil name (standardized)"
        data_tests:
          - not_null
      - name: data_nascimento
        description: "Birth date"
      - name: sexo
        description: "Gender"
        data_tests:
          - accepted_values:
              values: ['M', 'F', 'MASCULINO', 'FEMININO']

  - name: stg_deputado_historico
    description: "Staging table for deputado historical changes"
    columns:
      - name: deputado_id
        description: "Deputado identifier"
        data_tests:
          - not_null
      - name: data_inicio_vigencia
        description: "Start date of status period"
        data_tests:
          - not_null
      - name: id_legislatura
        description: "Legislature period ID"
      - name: sigla_partido
        description: "Political party"
      - name: sigla_uf
        description: "State abbreviation"
        data_tests:
          - accepted_values:
              values: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']

  - name: stg_despesas
    description: "Staging table for despesas with data cleansing"
    columns:
      - name: deputado_id
        description: "Foreign key to deputados"
        data_tests:
          - not_null
      - name: cod_documento
        description: "Document code"
        data_tests:
          - not_null
      - name: data_documento
        description: "Document date"
        data_tests:
          - not_null
      - name: valor_documento
        description: "Document value"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: valor_liquido
        description: "Net value"
        data_tests:
          - not_null
      - name: ano
        description: "Year"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2000
              max_value: 2030
      - name: mes
        description: "Month"
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
